# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('capacity_hours', models.ManyToManyField(to='amper.CapacityHour')),
            ],
        ),
        migrations.CreateModel(
            name='NasaReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('duration', models.PositiveIntegerField(help_text=b'in minutes')),
                ('consumption', models.PositiveIntegerField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amper.Item')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='reports',
            field=models.ManyToManyField(to='amper.Report'),
        ),
    ]
