# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0002_weatherdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.IntegerField()),
                ('azimut', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('solar_panel_angle', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('reflectance_angle', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('square_meters', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
