# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-30 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0002_auto_20170430_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, unique=True)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=8)),
                ('produced', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
