# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0002_auto_20170429_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
