# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0003_userconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='azimut',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='reflectance_angle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='solar_panel_angle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
