# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-30 02:43
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0003_realtimedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='consumption',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
