# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0004_delete_nasareport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
