# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-30 03:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0004_auto_20170430_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimedata',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='realtimedata',
            name='produced',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
