# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0004_auto_20170429_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacityhour',
            name='hour',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='hour',
            field=models.PositiveIntegerField(),
        ),
    ]
