# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0005_auto_20170429_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='capacity_hours',
        ),
        migrations.AddField(
            model_name='day',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
