# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0005_auto_20170429_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
