# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-30 05:12
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0005_auto_20170430_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('city', models.CharField(max_length=50)),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
