# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0006_auto_20170429_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='reports',
            field=models.ManyToManyField(blank=True, to='amper.Report'),
        ),
    ]
