# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-29 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amper', '0006_auto_20170429_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_completed',
        ),
    ]
